# Makefile.Host
TOP = ..
include $(TOP)/configure/CONFIG

DBD += drvAvme320.dbd
DBD += devAvme320.dbd

# Source files (for depends target):
#LIBSRCS += drvXy5320.c
#LIBSRCS += devXy5320.c

# Link everything into a library:
#LIBRARY_IOC_vxWorks = Xy5320
#LIBRARY_IOC_RTEMS   = Xy5320
#Xy5320_LIBS += Ipac

include $(TOP)/configure/RULES
